import { IGenericGetParams } from '../IGenericGetParams';

export interface IHostGetParams extends IGenericGetParams {
    groupids?: string | string[];
    applicationids?: string | string[];
    dserviceids?: string | string[];
    graphids?: string | string[];
    hostids?: string | string[];
    httptestids?: string | string[];
    interfaceids?: string | string[];
    itemids?: string | string[];
    maintenanceids?: string | string[];
    monitored_hosts?: boolean;
    proxy_hosts?: boolean;
    proxyids?: string | string[];
    templated_hosts?: boolean;
    templateids?: string | string[];
    triggerids?: string | string[];
    with_items?: boolean;
    with_applications?: boolean;
    with_graphs?: boolean;
    with_httptests?: boolean;
    with_monitored_httptests?: boolean;
    with_monitored_items?: boolean;
    with_monitored_triggers?: boolean;
    with_simple_graph_items?: boolean;
    with_triggers?: boolean;
    withInventory?: boolean;
    selectGroups?: any;
    selectApplications?: any;
    selectDiscoveries?: any;
    selectDiscoveryRule?: any;
    selectGraphs?: any;
    selectHostDiscovery?: any;
    selectHttpTests?: any;
    selectInterfaces?: any;
    selectInventory?: any;
    selectItems?: any;
    selectMacros?: any;
    selectParentTemplates?: any;
    selectScreens?: any;
    selectTriggers?: any;
    filter?: any;
    limitSelects?: number;
    search?: any;
    searchInventory?: any;
    sortfield?: string | string[];
}
